services:
  server:
    build: .
    ports:
      - "8210:8080"
    depends_on:
      - database
      - keycloak
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports: 
      - 8211:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:8211
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HOSTNAME_DEBUG=true
    command: start-dev
  
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=very_safe_password
      - POSTGRES_DB=deck-ranking
